title: "Fully Funded Scholarships & Jobs 2026-2027 | JobScholarGuide"
author: "JobScholarGuide"
url: "https://ekonet1.github.io"   # ✅ Root domain only
baseurl: "/jobscholarguide"        # ✅ Repository name

description: "Unlock global opportunities: scholarships, fellowships, internships, and jobs. Your roadmap to apply, qualify, and succeed in your career."

# Social links (uncomment if needed)
# twitter_username: jobscholarguide
# facebook_username: jobscholarguide
# linkedin_username: jobscholarguide
# github_username: ekonet1

show_excerpts: true   # ✅ Show excerpts on homepage

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"
  skin: dark
  custom_css:
    - /assets/css/custom.css   # ✅ Custom button + styling

# Control where excerpts cut
excerpt_separator: "<!--more-->"

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Feed settings
feed:
  path: rss.xml

# Sitemap settings
defaults:
  - scope:
      path: ""
    values:
      sitemap: true
